# Generated by Django 5.2.17 on 2026-09-10 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin_name",
                    models.CharField(max_length=200, verbose_name="Startsted"),
                ),
                ("origin_lat", models.FloatField(verbose_name="Start breddegrad")),
                ("origin_lng", models.FloatField(verbose_name="Start længdegrad")),
                (
                    "destination_name",
                    models.CharField(max_length=200, verbose_name="Destination"),
                ),
                (
                    "destination_lat",
                    models.FloatField(verbose_name="Destination breddegrad"),
                ),
                (
                    "destination_lng",
                    models.FloatField(verbose_name="Destination længdegrad"),
                ),
                ("departure_time", models.DateTimeField(verbose_name="Afgang cirka")),
                (
                    "max_detour_minutes",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Maksimal omvej i minutter"
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        choices=[
                            ("small_bag", "Lille taske"),
                            ("moving_box", "Flyttekasse"),
                            ("several_boxes", "Flere kasser"),
                            ("trunk", "Bagagerum"),
                            ("station_wagon", "Stationcar"),
                            ("van", "Varebil"),
                            ("trailer", "Trailer"),
                        ],
                        default="trunk",
                        max_length=20,
                        verbose_name="Ledig kapacitet",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("matched", "Matchet"),
                            ("completed", "Gennemført"),
                            ("cancelled", "Annulleret"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chauffør",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur",
                "verbose_name_plural": "Ture",
                "ordering": ["departure_time"],
            },
        ),
    ]
