# Generated by Django 5.2.17 on 2026-09-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Hvornår brugeren accepterede vilkårene ved oprettelse.",
                null=True,
                verbose_name="Vilkår accepteret",
            ),
        ),
    ]
