# Generated by Django 5.2.17 on 2026-09-10 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="source",
            field=models.CharField(
                choices=[("user", "Bruger"), ("auto", "Automatisk screening")],
                default="user",
                max_length=10,
                verbose_name="Kilde",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Anmelder",
            ),
        ),
    ]
