# Generated by Django 5.2.17 on 2026-09-10 20:13

import apps.transport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportrequest",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="opgaver/",
                validators=[apps.transport.models.validate_image_size],
                verbose_name="Billede",
            ),
        ),
    ]
