# Generated by Django 5.2.17 on 2026-09-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0002_transportrequest_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportrequest",
            name="terms_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Ejeren har bekræftet, at varen ikke er en forbudt genstand.",
                verbose_name="Vilkår bekræftet",
            ),
        ),
    ]
