# Generated by Django 5.2.17 on 2026-09-12 14:24

import apps.core.storage
import apps.transport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0003_transportrequest_terms_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transportrequest",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.core.storage.DatabaseStorage(),
                upload_to="opgaver/",
                validators=[apps.transport.models.validate_image_size],
                verbose_name="Billede",
            ),
        ),
    ]
