# Generated by Django 5.2.17 on 2026-09-10 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transport", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_score",
                    models.PositiveIntegerField(verbose_name="Matchscore i procent"),
                ),
                ("detour_km", models.FloatField(verbose_name="Omvej i km")),
                ("detour_minutes", models.FloatField(verbose_name="Omvej i minutter")),
                (
                    "suggested_price",
                    models.PositiveIntegerField(verbose_name="Foreslået pris i kr."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Foreslået"),
                            ("requested", "Forespurgt"),
                            ("accepted", "Accepteret"),
                            ("declined", "Afvist"),
                            ("expired", "Udløbet"),
                        ],
                        default="suggested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transport_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="transport.transportrequest",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["-match_score"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "transport_request"),
                        name="unique_trip_request_match",
                    )
                ],
            },
        ),
    ]
